import Link from 'next/link';
import { categories, featuredDownloads, creators } from '@/lib/data';

export default function Home(){return <main>
<section className="relative overflow-hidden"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top_left,rgba(249,115,22,.35),transparent_35%),radial-gradient(circle_at_bottom_right,rgba(59,130,246,.20),transparent_35%)]"/><div className="mx-auto grid max-w-7xl gap-10 px-5 py-24 md:grid-cols-2 md:items-center">
<div><p className="mb-4 inline-flex rounded-full border border-orange-500/30 bg-orange-500/10 px-4 py-2 text-sm font-semibold text-orange-600 dark:text-orange-300">Kostenlose Creator-Ressourcen · Community geprüft</p><h1 className="text-5xl font-black leading-tight md:text-7xl">Forge your content. Ohne Paywall.</h1><p className="mt-6 text-lg text-zinc-600 dark:text-zinc-300">CreatorForge ist eine freie Plattform für OBS Overlays, TikTok Live Assets, YouTube/Kick Ressourcen, StreamDeck Icons, Bots und Tools.</p><div className="mt-8 flex flex-wrap gap-4"><Link className="btn-primary" href="/downloads">Downloads ansehen</Link><Link className="btn-secondary" href="/upload">Eigenes Asset teilen</Link></div></div>
<div className="card shadow-glow"><div className="rounded-3xl bg-zinc-950 p-4 text-white"><div className="mb-4 flex gap-2"><span className="h-3 w-3 rounded-full bg-red-400"/><span className="h-3 w-3 rounded-full bg-yellow-400"/><span className="h-3 w-3 rounded-full bg-green-400"/></div><div className="rounded-2xl border border-white/10 bg-gradient-to-br from-orange-500/30 to-blue-500/20 p-8"><p className="text-sm uppercase tracking-widest text-orange-200">Featured Pack</p><h2 className="mt-4 text-3xl font-black">Neon Starter Pack</h2><p className="mt-3 text-white/70">OBS + TikTok Live + Start/Pause/End Screen</p><button className="mt-8 rounded-xl bg-white px-4 py-3 font-bold text-zinc-950">Kostenlos herunterladen</button></div></div></div>
</div></section>
<section className="mx-auto max-w-7xl px-5 py-12"><h2 className="text-3xl font-black">Kategorien</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map(c=><div key={c} className="card font-bold">{c}</div>)}</div></section>
<section className="mx-auto max-w-7xl px-5 py-12"><h2 className="text-3xl font-black">Beliebte Downloads</h2><div className="mt-6 grid gap-6 md:grid-cols-3">{featuredDownloads.map(d=><div key={d.title} className="card"><span className="rounded-full bg-orange-500/10 px-3 py-1 text-sm font-bold text-orange-600">{d.tag}</span><h3 className="mt-5 text-2xl font-black">{d.title}</h3><p className="mt-2 text-zinc-500">{d.type}</p><p className="mt-6 font-semibold">{d.downloads} Downloads</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-5 py-12"><h2 className="text-3xl font-black">Creator Spotlight</h2><div className="mt-6 grid gap-6 md:grid-cols-3">{creators.map(c=><div key={c.name} className="card"><div className="h-16 w-16 rounded-2xl bg-gradient-to-br from-orange-400 to-blue-500"/><h3 className="mt-5 text-2xl font-black">{c.name}</h3><p className="mt-2 text-zinc-500">{c.text}</p><p className="mt-4 text-sm font-bold text-orange-500">{c.platforms}</p></div>)}</div></section>
</main>}
